version: "3.8"

services:
  ikuai-taiyue:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-taiyue
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://61.50.125.98:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8000
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8000:8000"

  ikuai-changsha:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-changsha
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://218.76.0.124:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8001
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8001:8001"

  ikuai-shenzhen:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-shenzhen
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://219.134.95.147:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8002
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8002:8002"

  ikuai-shanghai:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-shanghai
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://ikuai.jiuwan.com:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8003
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8003:8003"

  ikuai-nuanshan:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-nuanshan
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://202.106.9.134:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8004
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8004:8004"

  ikuai-guangzhou:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-guangzhou
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://219.135.173.138:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8005
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8005:8005"

  ikuai-nuanshan_vpn:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-nuanshan_vpn
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://111.203.187.183:65432
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: jiankong
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: Tuyou@bcty123
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      # IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      # IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      # IKUAI_CRON_STREAM_DOMAIN_1:"10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8006
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8006:8006"