{
 "title": "IKUAI Dashboard",
 "description": "Monitor FRITZ!Box routers using prometheus and fritzbox_exporter",
 "tags": [
  "internet",
  "fritzbox",
  "prometheus"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\".*ikuai.*\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "table",
   "targets": [
    {
     "expr": "ikuai_version_system_str{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ikuai_sys_stat_cpu_temp{job=~\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"download\",job=~\"$job\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ]
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"total_down\",job=~\"$job\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "24h Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"total_down\",job=~\"$job\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(max(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "IP Connection Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"connect_num\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"upload\",job=~\"$job\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ]
    }
   ]
  },
  {
   "title": "Total Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"total_up\",job=~\"$job\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "24h Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ikuai_sys_stat_stream{type=\"total_up\",job=~\"$job\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "# WLAN Clients",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ikuai_iface_stream_connect_num{job=~\"$job\"}",
     "legendFormat": "{{comment}}-{{interface}}-{{ip_addr}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ikuai_sys_stat_cpu_used{job=~\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Download Bandwith",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream",
     "expr": "ikuai_iface_stream_download{job=~\"$job\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{comment}}-{{interface}}-{{ip_addr}}",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'receiverate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-receiverate,'downstream')"
    },
    {
     "alias": "upstream",
     "expr": "gateway_traffic_rate{direction=\"Received\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'sendrate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-sendrate,'upstream')"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "ikuai_sys_stat_memory", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Upload Bandwith",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream max",
     "expr": "ikuai_iface_stream_upload{job=~\"$job\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{comment}}-{{interface}}-{{ip_addr}}",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'downstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "downstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-downstreammax,'downstream max')"
    },
    {
     "alias": "upstream max",
     "expr": "gateway_traffic_rate{direction=\"Sent\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'upstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "upstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-upstreammax,'upstream max')"
    }
   ]
  },
  {
   "title": "ikuai client upload",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ikuai_client_upload{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ikuai protocol app stream upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Download",
     "expr": "increase(ikuai_protocol_app_stream_upload{job=~\"$job\"}[$__interval])",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "legendFormat": "{{name_cn}}",
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "ikuai client download",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "ikuai_client_download{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ikuai protocol app stream download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Download",
     "expr": "increase(ikuai_protocol_app_stream_download{job=~\"$job\"}[$__interval])",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "legendFormat": "{{name_cn}}",
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  }
 ]
}