{
 "title": "iKuai",
 "description": "iKuai OS dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "连接状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_up{id=\"host\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统版本",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_version{job=~\"$job\"}",
     "legendFormat": "iKuai {{ver_string}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_cpu_usage_ratio{job=~\"$job\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "线路流量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_upload_total_bytes{id!~\"device/.*|.*lan.*\",job=~\"$job\"}",
     "legendFormat": "上行 {{display}}"
    },
    {
     "expr": "ikuai_network_download_total_bytes{id!~\"device/.*|.*lan.*\",job=~\"$job\"}",
     "legendFormat": "下行 {{display}}"
    }
   ]
  },
  {
   "title": "设备数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_device_count{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_connect_count{id=\"host\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_uptime{id=\"host\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_memory_usage_kilo_bytes /ikuai_memory_size_kilo_bytes{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时上行",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_upload_speed_bytes{id=\"host\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时下行",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_download_speed_bytes{id=\"host\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备监控 - 实时",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ikuai_network_upload_speed_bytes{id=~\"device/.*\",job=~\"$job\"}-0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_download_speed_bytes{id=~\"device/.*\",job=~\"$job\"}-0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_connect_count{id=~\"device/.*\",job=~\"$job\"}-0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备监控 - 总计",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ikuai_network_upload_total_bytes{id=~\"device/.*\",job=~\"$job\"}-0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_download_total_bytes{id=~\"device/.*\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "历史上行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ikuai_network_upload_speed_bytes{id=~\"device/.*\",job=~\"$job\"}",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "历史下行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ikuai_network_download_speed_bytes{id=~\"device/.*\",job=~\"$job\"}",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "历史连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ikuai_network_connect_count{id=~\"device/.*\",job=~\"$job\"}",
     "legendFormat": "{{display}}"
    }
   ]
  }
 ]
}